"""empty message

Revision ID: 2d71be5da98e
Revises: 
Create Date: 2021-06-06 20:25:12.814090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d71be5da98e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('creditcard',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('vendor', sa.String(length=64), nullable=True),
    sa.Column('bank', sa.String(length=64), nullable=True),
    sa.Column('expiration', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id', 'number')
    )
    op.create_index(op.f('ix_creditcard_number'), 'creditcard', ['number'], unique=False)
    op.create_table('creditstatement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('close_date', sa.DateTime(), nullable=True),
    sa.Column('ars', sa.Float(), nullable=True),
    sa.Column('usd', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('balance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('bank', sa.String(length=64), nullable=True),
    sa.Column('account_n', sa.String(length=120), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('detail', sa.String(length=128), nullable=True),
    sa.Column('flow', sa.Integer(), nullable=True),
    sa.Column('bal', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=128), nullable=True),
    sa.Column('id_statement', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_statement'], ['creditstatement.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_balance_account_n'), 'balance', ['account_n'], unique=False)
    op.create_index(op.f('ix_balance_timestamp'), 'balance', ['timestamp'], unique=False)
    op.create_index(op.f('ix_balance_type'), 'balance', ['type'], unique=False)
    op.create_table('credit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('statement', sa.Integer(), nullable=True),
    sa.Column('card_number', sa.Integer(), nullable=True),
    sa.Column('card_code', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('transaction', sa.String(length=128), nullable=True),
    sa.Column('share', sa.String(length=64), nullable=True),
    sa.Column('purchase', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=64), nullable=True),
    sa.Column('type', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['card_number'], ['creditcard.number'], ),
    sa.ForeignKeyConstraint(['statement'], ['creditstatement.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credit_timestamp'), 'credit', ['timestamp'], unique=False)
    op.create_index(op.f('ix_credit_type'), 'credit', ['type'], unique=False)
    op.create_table('credittaxes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('statement', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=128), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['statement'], ['creditstatement.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('credittaxes')
    op.drop_index(op.f('ix_credit_type'), table_name='credit')
    op.drop_index(op.f('ix_credit_timestamp'), table_name='credit')
    op.drop_table('credit')
    op.drop_index(op.f('ix_balance_type'), table_name='balance')
    op.drop_index(op.f('ix_balance_timestamp'), table_name='balance')
    op.drop_index(op.f('ix_balance_account_n'), table_name='balance')
    op.drop_table('balance')
    op.drop_table('creditstatement')
    op.drop_index(op.f('ix_creditcard_number'), table_name='creditcard')
    op.drop_table('creditcard')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
