"""empty message

Revision ID: 755eddf13c02
Revises: 
Create Date: 2021-05-30 17:55:36.102110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '755eddf13c02'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('balance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('bank', sa.String(length=64), nullable=True),
    sa.Column('account_n', sa.String(length=120), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('detail', sa.String(length=128), nullable=True),
    sa.Column('flow', sa.Integer(), nullable=True),
    sa.Column('bal', sa.Integer(), nullable=True),
    sa.Column('tag', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_balance_account_n'), 'balance', ['account_n'], unique=False)
    op.create_index(op.f('ix_balance_tag'), 'balance', ['tag'], unique=False)
    op.create_index(op.f('ix_balance_timestamp'), 'balance', ['timestamp'], unique=False)
    op.create_table('credit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('bank', sa.String(length=64), nullable=True),
    sa.Column('card', sa.String(length=64), nullable=True),
    sa.Column('card_number', sa.Integer(), nullable=True),
    sa.Column('expiration', sa.DateTime(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('creditor', sa.String(length=128), nullable=True),
    sa.Column('share', sa.Integer(), nullable=True),
    sa.Column('ars', sa.Integer(), nullable=True),
    sa.Column('usd', sa.String(length=128), nullable=True),
    sa.Column('tag', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credit_card_number'), 'credit', ['card_number'], unique=False)
    op.create_index(op.f('ix_credit_tag'), 'credit', ['tag'], unique=False)
    op.create_index(op.f('ix_credit_timestamp'), 'credit', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_credit_timestamp'), table_name='credit')
    op.drop_index(op.f('ix_credit_tag'), table_name='credit')
    op.drop_index(op.f('ix_credit_card_number'), table_name='credit')
    op.drop_table('credit')
    op.drop_index(op.f('ix_balance_timestamp'), table_name='balance')
    op.drop_index(op.f('ix_balance_tag'), table_name='balance')
    op.drop_index(op.f('ix_balance_account_n'), table_name='balance')
    op.drop_table('balance')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
