"""empty message

Revision ID: d42f3a52a124
Revises: b4cc4c9992e3
Create Date: 2021-05-27 17:45:09.734555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd42f3a52a124'
down_revision = 'b4cc4c9992e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('creditor', sa.String(length=128), nullable=True),
    sa.Column('share', sa.Integer(), nullable=True),
    sa.Column('ars', sa.Integer(), nullable=True),
    sa.Column('usd', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credit_ars'), 'credit', ['ars'], unique=False)
    op.create_index(op.f('ix_credit_share'), 'credit', ['share'], unique=False)
    op.create_index(op.f('ix_credit_timestamp'), 'credit', ['timestamp'], unique=False)
    op.create_index(op.f('ix_credit_usd'), 'credit', ['usd'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_credit_usd'), table_name='credit')
    op.drop_index(op.f('ix_credit_timestamp'), table_name='credit')
    op.drop_index(op.f('ix_credit_share'), table_name='credit')
    op.drop_index(op.f('ix_credit_ars'), table_name='credit')
    op.drop_table('credit')
    # ### end Alembic commands ###
