"""empty message

Revision ID: e9ad861c35e0
Revises: d42f3a52a124
Create Date: 2021-05-28 16:01:29.318628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9ad861c35e0'
down_revision = 'd42f3a52a124'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credit', sa.Column('bank', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('credit', 'bank')
    # ### end Alembic commands ###
