"""empty message

Revision ID: fc91c20525e1
Revises: 0d0001b35961
Create Date: 2021-06-02 10:20:05.711258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc91c20525e1'
down_revision = '0d0001b35961'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credit', sa.Column('card_summary', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_credit_card_summary'), 'credit', ['card_summary'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_credit_card_summary'), table_name='credit')
    op.drop_column('credit', 'card_summary')
    # ### end Alembic commands ###
